{{- if .Values.wazuhIndexer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer
  namespace: {{ .Values.nameSpace }}
  labels:
    app: wazuh-indexer
#  {{- with .Values.wazuhIndexer.svcAnnotations }}
#  annotations:
#    {{- toYaml . | nindent 4 }}
#  {{- end }}
spec:
  selector:
    app: wazuh-indexer
  ports:
    - name: indexer-nodes
      port: {{ .Values.wazuhIndexer.nodePort }}
      targetPort: {{ .Values.wazuhIndexer.nodeTargetPort }}
  clusterIP: None
{{- end}}
