{{- if and (.Values.wazuhMaster.enabled) (.Values.wazuhWorkers.enabled) (.Values.wazuhCluster.enabled)}}
apiVersion: v1
kind: Service
metadata:
  name: wazuh  # Don't change, unless you update the Wazuh dashboard app config
  namespace: {{ .Values.nameSpace }}
  labels:
    app: wazuh-manager
    # dns: {{ required "wazuhManager.dns is required" .Values.wazuhManager.dns }}
  {{- with .Values.wazuhMaster.svcAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: api
      port: 55000
      targetPort: 55000
{{- end}}
