{{- if .Values.wazuhWorkers.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: {{ .Values.nameSpace }}
  labels:
    app: wazuh-manager
    # dns: {{ required "wazuh-workers.dns is required" .Values.wazuhWorkers.dns }}
  {{- with .Values.wazuhWorkers.svcAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: agents-events
      port: 1514
      targetPort: 1514
{{- end}}
