{{- if and (.Values.wazuhMaster.enabled) (.Values.wazuhWorkers.enabled) (.Values.wazuhCluster.enabled)}}
apiVersion: v1
kind: Service
metadata:
  name: wazuh  # Don't change, unless you update the Wazuh dashboard app config
  namespace: {{ .Values.nameSpace }}
  labels:
    app: wazuh-manager
    # dns: {{ .Values.wazuhManager.dns }}
  {{- with .Values.wazuhManager.svcAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: {{ .Values.wazuhManager.ports.regPort }}
      targetPort: {{ .Values.wazuhManager.ports.regTargetPort }}
    - name: api
      port: {{ .Values.wazuhManager.ports.apiPort }}
      targetPort: {{ .Values.wazuhManager.ports.apiTargetPort }}
{{- end}}
