# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh StorageClass

{{- if and (.Values.wazuh_master.enabled) (.Values.wazuh_workers.enabled) (.Values.wazuh_indexer.enabled)}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wazuh-storage
provisioner: {{ required "wazuh-sc.provisioner is required" .Values.wazuh_sc.provisioner }} 
# parameters:
#  encrypted: 'true'
#  type: gp2
# volumeBindingMode: WaitForFirstConsumer
# reclaimPolicy: Retain  # Useful in case you delete the PersistentVolumeClaim
{{- end}}
