{{- if and (.Values.wazuh_master.enabled) (.Values.wazuh_workers.enabled) (.Values.wazuh_cluster.enabled)}}
apiVersion: v1
kind: Service
metadata:
  name: wazuh  # Don't change, unless you update the Wazuh dashboard app config
  namespace: wazuh
  labels:
    app: wazuh-manager
    # dns: {{ required "wazuh_manager.dns is required" .Values.wazuh_manager.dns }}
  annotations:
    # domainName: {{ required "wazuh_manager.domain is required" .Values.wazuh_manager.domain }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: api
      port: 55000
      targetPort: 55000
{{- end}}
