{{- if .Values.wazuh-workers.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: wazuh
  labels:
    app: wazuh-manager
    # dns: {{ required "wazuh-workers.dns is required" .Values.wazuh-workers.dns }}
  annotations:
    # domainName: {{ required "wazuh-workers.domain is required" .Values.wazuh-workers.domain }}  
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: agents-events
      port: 1514
      targetPort: 1514
