{{- if .Values.wazuh-master.enabled and .Values.wazuh-worker.enabled adn .Values.wazuh-cluster.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: wazuh  # Don't change, unless you update the Wazuh dashboard app config
  namespace: wazuh
  labels:
    app: wazuh-manager
    # dns: {{ required "wazuh-manager.dns is required" .Values.wazuh-manager.dns }}
  annotations:
    # domainName: {{ required "wazuh-manager.domain is required" .Values.wazuh-manager.domain }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: api
      port: 55000
      targetPort: 55000