apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gophish-pvc
  namespace: {{ .Values.nameSpace }}
  labels:
    app: gophish
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
