{{- if .Values.wazuhMaster.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: upgrade-script
  namespace: {{ .Values.nameSpace }}
data:
{{ (.Files.Glob "files/auxi/upgrade.sh").AsConfig | indent 2 }}
{{- end}}
