{{- if .Values.wazuhMaster.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-conf
  namespace: {{ .Values.nameSpace }}
data:
  master.conf: {{ tpl ((.Files.Get "files/conf/wazuh_conf/master.conf") | quote) . }}
  worker.conf: {{ tpl ((.Files.Get "files/conf/wazuh_conf/worker.conf") | quote) . }}
{{- end}}
