{{- if .Values.wazuhIndexer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: indexer-configmap
  namespace: {{ .Values.nameSpace }}
data:
{{ (.Files.Glob "files/conf/indexer_conf/*").AsConfig | indent 2 }}
{{- end}}
