{{- if .Values.wazuhIndexer.sso.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-conf
  namespace: {{ .Values.nameSpace }}
data:
  config.yml: {{ tpl ((.Files.Get "files/conf/indexer_conf/config.yml") | quote) . }}
  roles_mapping.yml: {{ tpl ((.Files.Get "files/conf/indexer_conf/roles_mapping.yml") | quote) . }}
{{- end}}
