{{- if .Values.wazuhMaster.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: central-fim
  namespace: {{ .Values.nameSpace }}
data:
{{ (.Files.Glob "files/conf/centralized_fim/*").AsConfig | indent 2 }}
{{- end}}
