apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: main
      targetPort: 51820
      protocol: UDP
      port: 51820
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}
