wazuh_master:
  enabled: true
  authd_password: DefaultPassword
  replicas: 1
  image: 'wazuh/wazuh-manager:4.7.2'
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 512Mi
  volume_storage: 500Mi

wazuh_workers:
  enabled: true
  replicas: 1
  dns: route53
  domain: changeme.com # TODO: Change this for a Hosted Zone you configured in AWS Route 53
  image: 'wazuh/wazuh-manager:4.7.2'
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 512Mi
  volume_storage: 500Mi


wazuh_dashboard:
  enabled: true
  username: default
  password: DefaultPassword
  replicas: 1
  dns: route53
  domain: changeme.com
  balancer_cert: changeme
  image: 'wazuh/wazuh-dashboard:4.7.2'
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

wazuh_indexer:
  enabled: true
  username: admin
  password: DefaultPassword
  replicas: 1
  image: 'wazuh/wazuh-indexer:4.7.2'
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  volume_storage: 500M

wazuh_api:
  username: wazuh-wui
  password: DefaultPassword.1234

wazuh_cluster:
  enabled: true
  key: MTIzYTQ1YmM2N2RlZjg5MWdoMjNpNDVqazY3bDhtbjk=

wazuh_manager:
  dns: route53
  domain: changeme.com