ingress:
  enabled: true
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  host: "wazuh.schub.com"
#  tls: 
#    - hosts:
#      secretName: 

nameSpace: wazuh

wazuhCluster:
  enabled: true
  # This is the key that allows communication between the master and worker nodes.
  key: 123a45bc67def891gh23i45jk67l8mn9
  port: 1516
  targetPort: 1516

wazuhDashboard:
  enabled: true
  # This is de default user for the Wazuh dashboard. To change it's password you'll have to change the hash in the internalUsers field at the WazuhIndexer.
  # Add this comment to test versioning wazuh
  username: kibanaserver 
  password: kibanaserver 
  imageRepository: wazuh/wazuh-dashboard
  imageTag: '4.7.2'
  replicas: 1
  resources:
    requests:
      cpu: 
      memory: 
    limits:
      cpu: 500m
      memory: 1Gi
#  svcAnnotations:
#    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
#    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
  port: 443
  targetPort: 5601

wazuhIndexer:
  enabled: true
  # This is the default user to communicate the indexer and the dashboard. To change it's password it is important to change the hash at the WazuhIndexer.
  username: admin
  password: SecretPassword
  imageRepository: wazuh/wazuh-indexer
  imageTag: '4.7.2'
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  volumeStorage: 500Mi
  port: 9200
  targetPort: 9200
  nodePort: 9300
  nodeTargetPort: 9300
  internalUsers:
    _meta:
      type: "internalusers"
      config_version: 2

    admin:
      hash: "$2y$12$K/SpwjtB.wOHJ/Nc6GVRDuc1h0rM1DfvziFRNPtk27P.c4yDr9njO"
      reserved: true # Deleting a reserved user will result in the deployment not working.
      backend_roles:
      - "admin"
      description: "Demo admin user"

    kibanaserver:
      hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
      reserved: true # Deleting a reserved user will result in the deployment not working.
      description: "Demo kibanaserver user"

wazuhMaster:
  enabled: true
  # This is the password that the agent will use to enroll.
  authd_password: password 
  imageRepository: wazuh/wazuh-manager
  imageTag: '4.7.2'
  replicas: 1
  resources:
    requests:
      cpu: 
      memory: 
    limits:
      cpu: 400m
      memory: 512Mi
  volumeStorage: 500Mi
#  svcAnnotations:
#    # domainName: 'changeme'
#    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  # These are the credentials used to secure the API comunication between the Dashboard and the manager master node.
  wazuhApi: 
    username: wazuh-wui
    password: MyS3cr37P450r.*-

wazuhManager:
  ports:
    regPort: 1515
    regTargetPort: 1515 
    apiPort: 55000
    apiTargetPort: 55000

wazuhStorageClass:
  provisioner: k8s.io/minikube-hostpath

wazuhWorkers:
  enabled: true
  imageRepository: wazuh/wazuh-manager
  imageTag: '4.7.2'
  replicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi
  volumeStorage: 500Mi
#  svcAnnotations:
#    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  port: 1514
  targetPort: 1514

