{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "application.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: {{ .Values.autoscaling.cpu.type }}
          averageValue: {{ .Values.autoscaling.cpu.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- range $k, $v := .Values.autoscaling.customMetrics }}
    - type: Object
      object:
        metric:
          name: {{ $v.name }}
        describedObject:
          apiVersion: {{ $v.describedObject.apiVersion }}
          kind: {{ $v.describedObject.kind }}
          name: {{ $v.describedObject.name }}
        target:
          type: Value
          value: {{ $v.target.value }}
    {{- end }} 
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: {{ .Values.autoscaling.memory.type }}
          averageValue: {{ .Values.autoscaling.memory.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
