{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "application.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4}}
  hostnames:
    {{- toYaml .Values.httpRoute.hostNames | nindent 4}}
  rules:
    {{- toYaml .Values.httpRoute.rules | nindent 4}}
{{- end }}
