{{- if .Values.service }}
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "application.labels.application" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.service.additionalLabels }}
{{ toYaml .Values.service.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ include "application.tplvalues.render" ( dict "value" .Values.service.annotations  "context" $ ) | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
  namespace: {{ template "application.namespace" $ }}
spec:
{{- if .Values.service.type }}  
  type: "{{ .Values.service.type }}"
{{- end }}
  selector:
{{ include "application.labels.selector" . | indent 4 }}
{{- if .Values.deployment.podLabels }}
{{ toYaml .Values.deployment.podLabels | indent 4 }}
{{- end }}
  ports:
  {{- if .Values.deployment.openshiftOAuthProxy.enabled }}
  - name: proxy
    port: 443
    protocol: TCP
    targetPort: 8443
  {{- else }}
{{ toYaml .Values.service.ports | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}