apiVersion: v1
kind: Secret
metadata:
  name: indexer-certs
  namespace: wazuh
type: Opaque
data:
  admin-key.pem: |
{{ .Files.Get "files/certs/indexer_cluster/admin-key.pem" | b64enc | indent 4 }}
  admin.pem: |
{{ .Files.Get "files/certs/indexer_cluster/admin.pem" | b64enc | indent 4 }}
  dashboard-key.pem: |
{{ .Files.Get "files/certs/indexer_cluster/dashboard-key.pem" | b64enc | indent 4 }}
  dashboard.pem: |
{{ .Files.Get "files/certs/indexer_cluster/dashboard.pem" | b64enc | indent 4 }}
  filebeat-key.pem: |
{{ .Files.Get "files/certs/indexer_cluster/filebeat-key.pem" | b64enc | indent 4 }}
  filebeat.pem: |
{{ .Files.Get "files/certs/indexer_cluster/filebeat.pem" | b64enc | indent 4 }}
  node-key.pem: |
{{ .Files.Get "files/certs/indexer_cluster/node-key.pem" | b64enc | indent 4 }}
  node.pem: |
{{ .Files.Get "files/certs/indexer_cluster/node.pem" | b64enc | indent 4 }}
  root-ca.pem: |
{{ .Files.Get "files/certs/indexer_cluster/root-ca.pem" | b64enc | indent 4 }}
