# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh master StatefulSet

{{- if .Values.wazuhMaster.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: {{ required "wazuh-master.replicas is required" .Values.wazuhMaster.replicas }}
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: wazuh-cluster
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
      name: wazuh-manager-master
    spec:
      volumes:
        - name: config
          configMap:
            name: wazuh-conf
        - name: filebeat-certs
          secret:
            secretName: indexer-certs
        - name: upgrade-certs
          secret:
            secretName: upgrade-certs
        - name: wazuh-authd-pass
          secret:
            secretName: wazuh-authd-pass
        - name: wazuh-manager-master
          persistentVolumeClaim:
            claimName: wazuh-manager-master-pvc
        - name: central-conf
          configMap:
            name: central-fim
        - name: slack-integration
          configMap:
            name: custom-slack
        - name: wpk-volume
          persistentVolumeClaim:
            claimName: wazuh-master-wpk-pvc
      securityContext:
        fsGroup: 101
      initContainers:
        - name: mac-os-wpk
          image: python:3.12-slim
          volumeMounts:
            - name: wpk-volume
              mountPath: /var/ossec/wpk
            - name: upgrade-certs
              mountPath: /var/ossec/wpk/wpk_root.key
              readOnly: true
              subPath: wpk_root.key
            - name: upgrade-certs
              mountPath: /var/ossec/wpk/wpk_root.pem
              readOnly: true
              subPath: wpk_root.pem
            - name: upgrade-certs
              mountPath: /var/ossec/wpk/wpkcert.key
              readOnly: true
              subPath: wpkcert.key
            - name: upgrade-certs
              mountPath: /var/ossec/wpk/wpkcert.pem
              readOnly: true
              subPath: wpkcert.pem
            - name: upgrade-certs
              mountPath: /var/ossec/wpk/wpkcert.csr
              readOnly: true
              subPath: wpkcert.csr
            - name: upgrade-certs
              mountPath: /var/ossec/wpk/wpk_root.srl
              readOnly: true
              subPath: wpk_root.srl
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt update
              apt install curl -y
              pip install cryptography
              cd /var/ossec/wpk
              curl -Ls https://github.com/wazuh/wazuh/archive/v{{ .Values.wazuhMaster.imageTag }}.tar.gz | tar zx
              curl -Ls https://packages.wazuh.com/4.x/macos/wazuh-agent-{{ .Values.wazuhMaster.imageTag }}-1.pkg --output wazuh-{{ .Values.wazuhMaster.imageTag }}/wazuh-agent-{{ .Values.wazuhMaster.imageTag }}-1.pkg
              cp ./wpk_root.pem wazuh-{{ .Values.wazuhMaster.imageTag }}/etc/wpk_root.pem
              cp wazuh-{{ .Values.wazuhMaster.imageTag }}/src/init/pkg_installer.sh wazuh-{{ .Values.wazuhMaster.imageTag }}/.
              wazuh-{{ .Values.wazuhMaster.imageTag }}/tools/agent-upgrade/wpkpack.py ./Mac_OS_agent.wpk ./wpkcert.pem ./wpkcert.key wazuh-{{ .Values.wazuhMaster.imageTag }}/wazuh-agent-{{ .Values.wazuhMaster.imageTag }}-1.pkg wazuh-{{ .Values.wazuhMaster.imageTag }}/upgrade.sh wazuh-{{ .Values.wazuhMaster.imageTag }}/pkg_installer.sh
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
      containers:
        - name: wazuh-manager
          image: "{{ .Values.wazuhMaster.imageRepository }}:{{ .Values.wazuhMaster.imageTag }}"
          resources: 
            limits:
              cpu: {{ .Values.wazuhMaster.resources.limits.cpu }}
              memory: {{ .Values.wazuhMaster.resources.limits.memory }}
            requests:
              cpu: {{ .Values.wazuhMaster.resources.requests.cpu }}
              memory: {{ .Values.wazuhMaster.resources.requests.memory }}
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - name: slack-integration
              mountPath: /wazuh-config-mount/integrations/slack.py
              subPath: slack.py
            - name: config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: master.conf
              readOnly: true
            - name: central-conf
              mountPath: /var/ossec/etc/shared/Linux/agent.conf
              subPath: Linux.conf
            - name: central-conf
              mountPath: /var/ossec/etc/shared/Windows/agent.conf
              subPath: Windows.conf
            - name: central-conf
              mountPath: /var/ossec/etc/shared/MacOS/agent.conf
              subPath: MacOS.conf
            - name: filebeat-certs
              mountPath: /etc/ssl/root-ca.pem
              readOnly: true
              subPath: root-ca.pem
            - name: filebeat-certs
              mountPath: /etc/ssl/filebeat.pem
              subPath: filebeat.pem
              readOnly: true
            - name: filebeat-certs
              mountPath: /etc/ssl/filebeat.key
              subPath: filebeat-key.pem
              readOnly: true
            - name: wazuh-authd-pass
              mountPath: /wazuh-config-mount/etc/authd.pass
              subPath: authd.pass
              readOnly: true
            - name: wazuh-manager-master
              mountPath: /var/ossec/api/configuration
              subPath: wazuh/var/ossec/api/configuration
            - name: wazuh-manager-master
              mountPath: /var/ossec/etc
              subPath: wazuh/var/ossec/etc
            - name: wazuh-manager-master
              mountPath: /var/ossec/logs
              subPath: wazuh/var/ossec/logs
            - name: wazuh-manager-master
              mountPath: /var/ossec/queue
              subPath: wazuh/var/ossec/queue
            - name: wazuh-manager-master
              mountPath: /var/ossec/var/multigroups
              subPath: wazuh/var/ossec/var/multigroups
            - name: wazuh-manager-master
              mountPath: /var/ossec/integrations
              subPath: wazuh/var/ossec/integrations
            - name: wazuh-manager-master
              mountPath: /var/ossec/active-response/bin
              subPath: wazuh/var/ossec/active-response/bin
            - name: wazuh-manager-master
              mountPath: /var/ossec/agentless
              subPath: wazuh/var/ossec/agentless
            - name: wazuh-manager-master
              mountPath: /var/ossec/wodles
              subPath: wazuh/var/ossec/wodles
            - name: wazuh-manager-master
              mountPath: /etc/filebeat
              subPath: filebeat/etc/filebeat
            - name: wazuh-manager-master
              mountPath: /var/lib/filebeat
              subPath: filebeat/var/lib/filebeat
            - name: wpk-volume
              mountPath: /var/ossec/wpk
          ports: 
            - containerPort: {{ .Values.wazuhManager.ports.regPort }}
              name: registration
            - containerPort: {{ .Values.wazuhCluster.port }}
              name: cluster
            - containerPort: {{ .Values.wazuhManager.ports.apiPort }}
              name: api
          env:
            - name: INDEXER_URL
              value: https://indexer:9200
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: username
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: password
            - name: FILEBEAT_SSL_VERIFICATION_MODE
              value: 'full'
            - name: SSL_CERTIFICATE_AUTHORITIES
              value: /etc/ssl/root-ca.pem
            - name: SSL_CERTIFICATE
              value: /etc/ssl/filebeat.pem
            - name: SSL_KEY
              value: /etc/ssl/filebeat.key
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password
            - name: WAZUH_CLUSTER_KEY
              valueFrom:
                secretKeyRef:
                  name: wazuh-cluster-key
                  key: key
{{- end}}
