{{- if .Values.wazuhWorkers.ingress.enabled -}}
apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazuh-ingress
  namespace: {{ .Values.nameSpace }}
  {{- with .Values.wazuhWorkers.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.wazuhWorkers.ingress.tls }}
  tls:
    {{- range .Values.wazuhWorkers.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.wazuhWorkers.ingress.communicationHost }}
      http:
        paths:
          - backend:
              service:
                name: wazuh-workers
                port:
                  number: {{ .Values.wazuhWorkers.port }}
            path: /
            pathType: Prefix
{{- end -}}
