{{- if .Values.postfix.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postfix-statefulset
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
      node-type: main
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: postfix
        node-type: main
      name: postfix
    spec:
      volumes:
        - name: postfix-config
          configMap:
            name: postfix-conf
        - name: opendkim-config
          configMap:
            name: opendkim-conf
        - name: opendkim-certs
          secret:
            secretName: opendkim-certs
        - name: resolv-conf
          hostPath:
            path: /etc/resolv.conf
            type: File
        - name: postfix-writable-main
          emptyDir: {}
      securityContext:
        fsGroup: 101
      initContainers:
        - name: copy-postfix-config
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              cp /tmp/postfix-conf/main.cf /tmp/writeable-postfix-conf/main.cf
          volumeMounts:
            - name: postfix-config
              mountPath: /tmp/postfix-conf
            - name: postfix-writable-main
              mountPath: /tmp/writeable-postfix-conf
      containers:
        - name: postfix
          image: "ghcr.io/schub-cloud/docker-images:gophish-postfix-4d9b39"
          resources: 
            limits:
              cpu: {{ .Values.postfix.resources.limits.cpu }}
              memory: {{ .Values.postfix.resources.limits.memory }}
            requests:
              cpu: {{ .Values.postfix.resources.requests.cpu }}
              memory: {{ .Values.postfix.resources.requests.memory }}
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - name: postfix-writable-main
              mountPath: /etc/postfix/main.cf
              subPath: main.cf
            - name: postfix-config
              mountPath: /etc/aliases
              subPath: aliases
            - name: postfix-config
              mountPath: /etc/mailname
              subPath: mailname
            - name: opendkim-config
              mountPath: /etc/opendkim.conf
              subPath: opendkim.conf
            - name: opendkim-config
              mountPath: /etc/opendkim/SigningTable
              subPath: SigningTable
            - name: opendkim-config
              mountPath: /etc/opendkim/KeyTable
              subPath: KeyTable
            - name: opendkim-config
              mountPath: /etc/opendkim/TrustedHosts
              subPath: TrustedHosts
            - name: opendkim-certs
              mountPath: /etc/opendkim/keys/schub.cloud
              subPath: default.private
            - name: resolv-conf
              mountPath: /var/spool/postfix/etc/resolv.conf
{{- end}}
