nameSpace: addons

goPhish:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi
  svcPorts:
    communication:
      port: 80
      targetPort: 8080
    dashboard:
      port: 3333
      targetPort: 3333
  ingress:
    dashboard:
      host: "gophish.schub.cloud"
    #  annotations:
    #    kubernetes.io/ingress.class: nginx
    #    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #  tls: 
    #    - hosts:
    #      secretName: 
    server:
      host: "gophish.server.schub.cloud"
    #  annotations:
    #    kubernetes.io/ingress.class: nginx
    #    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #  tls: 
    #    - hosts:
    #      secretName: 
