nameSpace: addons

goPhish:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi
  svcPorts:
    communication:
      port: 80
      targetPort: 8080
    dashboard:
      port: 3333
      targetPort: 3333
  ingress:
    dashboard:
      host: "gophish.schub.cloud"
    #  annotations:
    #    kubernetes.io/ingress.class: nginx
    #    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #  tls: 
    #    - hosts:
    #      secretName: 
    server:
      host: "gophish.server.schub.cloud"
    #  annotations:
    #    kubernetes.io/ingress.class: nginx
    #    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #  tls: 
    #    - hosts:
    #      secretName: 

postfix:
  email: default-email@schub.cloud
  email_password: default_password
  port: 25
  mail_name: schub.cloud
  smtp_domain: smtp.outlook.com
  smtp_port: 587
  resources:
    requests:
      cpu: 0.5
      memory: 500Mi
    limits:
      cpu: 1
      memory: 1Gi
