{{- if .Values.wazuhIndexer.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer
  namespace: wazuh
  labels:
    app: wazuh-indexer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wazuh-storage
  resources:
    requests:
      storage: {{ .Values.wazuhIndexer.volumeStorage }} 
{{- end}}
