{{- if .Values.wazuhMaster.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-worker-wpk-pvc
  namespace: wazuh
  labels:
    app: wazuh-manager
    node-type: worker
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: wazuh-storage
  resources:
    requests:
      storage: 20G 
{{- end}}
