{{- if .Values.wazuhMaster.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-master-wpk-pvc
  namespace: wazuh
  labels:
    app: wazuh-manager
    node-type: master
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wazuh-storage
  resources:
    requests:
      storage: 20G 
{{- end}}
