{{- if .Values.wazuhMaster.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-managers-wpk-pvc
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: wazuh-wpk-sc
  resources:
    requests:
      storage: 20G 
{{- end}}
