{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.clusterName }}
  labels:
    {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    {{- range .Values.serviceMonitor.endpoints }}
    - port: {{ .port }}
      path: {{ .path }}
      scheme: {{ .scheme }}
      interval: {{ .interval }}
      scrapeTimeout: {{ .scrapeTimeout }}
    {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.clusterName }}-server
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
