{{- if .Values.clusterPolicy.enabled }}
{{ $clusterName := .Values.clusterName }}
{{ $releaseNamespace := .Release.Namespace }}
{{ range $userName, $userSpec := .Values.users }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $clusterName }}-{{ $userName }}-sync-secret
spec:
  generateExisting: true
  background: false
  rules:
  - name: {{ $clusterName }}-{{ $userName }}-secret
    skipBackgroundRequests: true
    match:
      resources:
        kinds:
        - Namespace
        names:
{{ range $namespace, $value := $userSpec.credentialsNamespaces -}}
{{ printf "- %s" $namespace | indent 8 }}
{{ end }}
    generate:
        apiVersion: v1
        kind: Secret
        name: {{ $userName }}-user-credentials
        namespace: {{ `"{{request.object.metadata.name}}"` }}
        synchronize: true
        clone:
            namespace: {{ $releaseNamespace }}
            name: {{ $userName }}-user-credentials
{{ end }}
{{- end }}