# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh authd password secret

{{- if .Values.wazuhMaster.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
  namespace: {{ .Values.nameSpace }}
data:
  authd.pass: {{ required "authd.password is required" .Values.wazuhMaster.authd_password | b64enc }} 
{{- end}}
