{{- if .Values.wazuhIndexer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: indexer-certs
  namespace: {{ .Values.nameSpace }}
type: Opaque
data:
  admin-key.pem: |
{{ .Files.Get "files/certs/indexer/admin-key.pem" | b64enc | indent 4 }}
  admin.pem: |
{{ .Files.Get "files/certs/indexer/admin.pem" | b64enc | indent 4 }}
  dashboard-key.pem: |
{{ .Files.Get "files/certs/indexer/dashboard-key.pem" | b64enc | indent 4 }}
  dashboard.pem: |
{{ .Files.Get "files/certs/indexer/dashboard.pem" | b64enc | indent 4 }}
  filebeat-key.pem: |
{{ .Files.Get "files/certs/indexer/filebeat-key.pem" | b64enc | indent 4 }}
  filebeat.pem: |
{{ .Files.Get "files/certs/indexer/filebeat.pem" | b64enc | indent 4 }}
  node-key.pem: |
{{ .Files.Get "files/certs/indexer/node-key.pem" | b64enc | indent 4 }}
  node.pem: |
{{ .Files.Get "files/certs/indexer/node.pem" | b64enc | indent 4 }}
  root-ca.pem: |
{{ .Files.Get "files/certs/indexer/root-ca.pem" | b64enc | indent 4 }}
{{- end}}
