{{- if .Values.wazuhMaster.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: upgrade-certs
  namespace: {{ .Values.nameSpace }}
type: Opaque
data:
  wpk_root.key: |
{{ .Values.wazuhMaster.upgrade_certs.wpk_root_key | indent 4 }}
  wpk_root.pem: |
{{ .Values.wazuhMaster.upgrade_certs.wpk_root_pem | indent 4 }}
  wpkcert.key: |
{{ .Values.wazuhMaster.upgrade_certs.wpkcert_key | indent 4 }}
  wpkcert.pem: |
{{ .Values.wazuhMaster.upgrade_certs.wpkcert_pem | indent 4 }}
  wpkcert.csr: |
{{ .Values.wazuhMaster.upgrade_certs.wpkcert_csr | indent 4 }}
  wpk_root.srl: |
{{ .Values.wazuhMaster.upgrade_certs.wpk_root_srl | indent 4 }}
{{- end}}
