{{- if .Values.wazuhIndexer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: indexer-certs
  namespace: {{ .Values.nameSpace }}
type: Opaque
data:
  admin-key.pem: |
{{ .Values.wazuhIndexer.certs.adminKey | indent 4 }}
  admin.pem: |
{{ .Values.wazuhIndexer.certs.admin | indent 4 }}
  dashboard-key.pem: |
{{ .Values.wazuhIndexer.certs.dashboardKey | indent 4 }}
  dashboard.pem: |
{{ .Values.wazuhIndexer.certs.dashboard | indent 4 }}
  filebeat-key.pem: |
{{ .Values.wazuhIndexer.certs.filebeatKey | indent 4 }}
  filebeat.pem: |
{{ .Values.wazuhIndexer.certs.filebeat | indent 4 }}
  node-key.pem: |
{{ .Values.wazuhIndexer.certs.nodeKey | indent 4 }}
  node.pem: |
{{ .Values.wazuhIndexer.certs.node | indent 4 }}
  root-ca.pem: |
{{ .Values.wazuhIndexer.certs.rootca | indent 4 }}
{{- end}}