apiVersion: v1
kind: Secret
metadata:
  name: wireguard
  namespace: example
type: Opaque
stringData:
  wg0.conf.template: |
    [Interface]
    Address = 10.0.0.1/24
    ListenPort = 51820
    PrivateKey = ""

    [Peer]
    PublicKey = ""
    AllowedIPs = 0.0.0.0/0
