apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: rabbitmq-server-scaling-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Object
    object:
      metric:
        name: rabbitmq_queue_messages
      describedObject:
        apiVersion: "v1"
        kind: Service
        name: rabbitmq-server-scaling-demo
      target:
        type: Value
        value: 100
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30