name: Create PR Wazuh
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new branch
        run: git checkout -b temporary-branch/wazuh-version-${{ steps.version.outputs.version }}

      - name: Install helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
          minor-identifier: "feat:"
          prefix: wazuh-

      - name: Install yq
        id: setup-yq
        uses: shiipou/setup-yq-action@v2.2.0

      - name: Echo Tags
        run: |
          echo "TAG=$(echo ${{ steps.version.outputs.version }} | cut -c 8-13)" >> $GITHUB_ENV

      - name: Upgrade Version
        run: |
          cd wazuh
          yq -i ".version = \"${{ env.TAG }}\"" Chart.yaml
          cd ..

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "AUTO: Bump Wazuh Helm Chart version to ${{ steps.version.outputs.version }}."
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: "temporary-branch/wazuh-version-${{ steps.version.outputs.version }}"
          delete-branch: true
          title: 'wazuh-version-${{ steps.version.outputs.version }}'
          labels: |
            automated pr
          add-paths: wazuh/Chart.yaml
