name: Create PR GoPhish
on:
  workflow_dispatch:
    inputs:
        version:
          type: string
          required: true
          description: "New gophish helm chart version x.y.z."
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install yq
        id: setup-yq
        uses: shiipou/setup-yq-action@v2.2.0

      - name: Echo Tags
        run: |
          echo "TAG=$(echo ${{ inputs.version }})" >> $GITHUB_ENV

      - name: Upgrade Version
        run: |
          cd gophish
          yq -i ".version = \"${{ env.TAG }}\"" Chart.yaml
          cd ..

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "AUTO: Bump GoPhish Helm Chart version to ${{ inputs.version }}."
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: "temporary-gophish-branch/${{ inputs.version }}"
          delete-branch: true
          title: 'gophish-${{ inputs.version }}'
          labels: |
            automated pr
          add-paths: gophish/Chart.yaml
