name: Deploy Wazuh

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set Up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Deploy Helm chart
        run: |
          helm upgrade --install wazuh helm-charts/wazuh -n wazuh --create-namespace
